import { Text } from '@/components/AppText';
import Ionicons from '@react-native-vector-icons/ionicons';
import { zodResolver } from '@hookform/resolvers/zod';
import { router } from '@/navigation/router';
import { Controller, useForm, useWatch } from 'react-hook-form';
import { Pressable, StyleSheet, View } from 'react-native';
import { Button, Card, Input, Screen, ui } from '@/components/ui';
import { colors } from '@/constants/theme';
import { loginSchema, type LoginValues } from '@/features/auth/schema';
import { useAuthStore } from '@/store/authStore';

export default function Login(){
  const signIn=useAuthStore(s=>s.signIn); const {control,handleSubmit,setValue,formState:{errors,isSubmitting}}=useForm<LoginValues>({resolver:zodResolver(loginSchema),defaultValues:{identifier:'+92 300 1234567',password:'airmax123',role:'customer'}}); const role=useWatch({control,name:'role'});
  const submit=async(v:LoginValues)=>{await new Promise<void>(r=>setTimeout(r,450));signIn(v.role,v.identifier);router.replace(v.role==='admin'?'/(admin)':'/(customer)')};
  return <Screen><View style={styles.brand}><View style={styles.logo}><Ionicons name="wifi" size={31} color={colors.primary}/></View><Text style={styles.name}>AIRMAX</Text><Text style={ui.body}>Faster Connection, Better Life</Text></View><Card><Text style={styles.heading}>Welcome back</Text><Text style={[ui.body,{marginTop:5,marginBottom:20}]}>Sign in to manage your connection.</Text><View style={styles.switch}><Pressable onPress={()=>setValue('role','customer')} style={[styles.switchItem,role==='customer'&&styles.active]}><Text style={[styles.switchText,role==='customer'&&styles.activeText]}>Customer</Text></Pressable><Pressable onPress={()=>setValue('role','admin')} style={[styles.switchItem,role==='admin'&&styles.active]}><Text style={[styles.switchText,role==='admin'&&styles.activeText]}>Admin</Text></Pressable></View><Controller control={control} name="identifier" render={({field:{onChange,onBlur,value}})=><Input label="Phone or email" icon="person-outline" value={value} onChangeText={onChange} onBlur={onBlur} autoCapitalize="none" error={errors.identifier?.message}/>}/><Controller control={control} name="password" render={({field:{onChange,onBlur,value}})=><Input label="Password" icon="lock-closed-outline" value={value} onChangeText={onChange} onBlur={onBlur} secureTextEntry error={errors.password?.message}/>}/><Pressable onPress={()=>router.push('/(auth)/forgot')}><Text style={styles.forgot}>Forgot password?</Text></Pressable><Button title="Sign in" icon="arrow-forward" loading={isSubmitting} onPress={handleSubmit(submit)}/><Button title="Sign in with OTP" variant="secondary" icon="phone-portrait-outline" onPress={()=>router.push('/(auth)/otp')}/></Card><Pressable onPress={()=>router.push('/customer/install')}><Text style={styles.install}>New to AIRMAX? <Text style={{color:colors.primary,fontWeight:'800'}}>Request installation</Text></Text></Pressable></Screen>;
}
const styles=StyleSheet.create({brand:{alignItems:'center',paddingTop:34,paddingBottom:28},logo:{width:64,height:64,borderRadius:20,backgroundColor:'#092347',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.primary},name:{fontSize:29,fontWeight:'900',color:colors.text,letterSpacing:4,marginTop:12},heading:{color:colors.text,fontSize:23,fontWeight:'800'},switch:{flexDirection:'row',backgroundColor:colors.background,borderRadius:12,padding:4,marginBottom:20},switchItem:{flex:1,padding:11,alignItems:'center',borderRadius:9},active:{backgroundColor:colors.surface2},switchText:{color:colors.muted,fontWeight:'700'},activeText:{color:colors.primary},forgot:{color:colors.primary,textAlign:'right',fontWeight:'700',fontSize:13,marginTop:-4,marginBottom:4},install:{color:colors.muted,textAlign:'center',marginTop:22,fontSize:13}});
